# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            C&eacute;sar D. Velandia
tagline:          Github-hosted log
url:              http://cesarvelandia.github.io
paginate:         1
baseurl:          /
author:
  name:           C&eacute;sar Velandia
  url:            https://twitter.com/cesardvelandia
  email:          c@cesarvelandia.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/cesarvelandia/cesarvelandia.github.io

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
	
