# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Cesar D. Velandia
tagline:          A Jekyll-powered online notebook
url:              http://cesarvelandia.github.io
paginate:         1
baseurl:          /
author:
  name:           Cesar Velandia
  url:            https://twitter.com/cesardvelandia
  email:          c@cesarvelandia.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/cesarvelandia/cesarvelandia.github.io

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
